services:
  db:
    image: postgres:15
    container_name: salesapp_db
    restart: always
    environment:
      POSTGRES_PASSWORD: parool
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: