services:
  db:
    image: postgres:15
    container_name: salesapp_db
    restart: always
    environment:
      POSTGRES_PASSWORD: parool
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./SalesApp.Server
      dockerfile: Dockerfile.prod
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DbString: "Host=db;Port=5432;Database=salesdb;Username=postgres;Password=parool"
    ports:
      - "8080:8080"
    depends_on:
      - db

  client:
    build: ./salesapp.client
    ports:
      - "5173:80"
    depends_on:
      - server
    environment:
    - VITE_API_URL=http://localhost:8080

volumes:
  postgres_data:
